name: "FRP Client (Custom)"
version: "0.56.3"
slug: "my_frpc"
description: "My personal FRP Client Add-on (v0.56.3)"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
map:
  - homeassistant_config:rw
